steps:
- id: 'install npm'
  name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- id: 'deploy cloud functions'
  name: "gcr.io/cloud-builders/gcloud"
  dir: 'cloudFunctions'
  args: ['functions','deploy','syncProducer','--source=.','--runtime=nodejs6','--trigger-http']